# Generated by Django 3.2.9 on 2021-11-26 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_activity_extendeduser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoes',
            name='id',
            field=models.CharField(editable=False, max_length=15, primary_key=True, serialize=False),
        ),
    ]
