# Generated by Django 3.2.9 on 2021-12-20 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_shoes_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoes',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='shoes',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
