# Generated by Django 3.2.9 on 2021-12-20 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20211220_1649'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='price',
        ),
    ]
